# Generated by Django 5.0.6 on 2024-06-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_contact_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
    ]
