# Generated by Django 5.0.6 on 2024-06-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_comment_contact_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intro_Name', models.CharField(max_length=50)),
                ('Intro_p', models.TextField()),
            ],
        ),
    ]
