# Generated by Django 5.0.6 on 2024-06-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intro',
            old_name='Intro_p',
            new_name='Intro_par',
        ),
    ]
