# Generated by Django 5.0.6 on 2024-06-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_intro_p_intro_intro_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='Intro_Name',
            field=models.CharField(max_length=100),
        ),
    ]
