# Generated by Django 5.0.6 on 2024-06-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_intro_image_alter_intro_intro_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Row1_Inst_Name', models.CharField(max_length=100)),
                ('Row1_Degree_Name', models.CharField(max_length=100)),
                ('Row1_Year', models.CharField(max_length=100)),
                ('Row2_Inst_Name', models.CharField(max_length=100)),
                ('Row2_Degree_Name', models.CharField(max_length=100)),
                ('Row2_Year', models.CharField(max_length=100)),
                ('Row3_Inst_Name', models.CharField(max_length=100)),
                ('Row3_Degree_Name', models.CharField(max_length=100)),
                ('Row3_Year', models.CharField(max_length=100)),
            ],
        ),
    ]
