# Generated by Django 5.0.6 on 2024-06-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
