# Generated by Django 5.0.6 on 2024-06-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_s_delete_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=100)),
                ('desc1', models.CharField(max_length=100)),
                ('desc2', models.CharField(max_length=100)),
                ('desc3', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='S',
        ),
    ]
