# Generated by Django 5.0.6 on 2024-07-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_skill_delete_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intro_Name', models.CharField(max_length=100)),
                ('Intro_Status', models.CharField(max_length=100)),
                ('Intro_par', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Intro',
        ),
    ]
