# Generated by Django 5.0.6 on 2024-07-01 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_i_delete_intro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='I',
            new_name='Intro',
        ),
    ]
