# Generated by Django 5.0.6 on 2024-07-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_skill_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='c++.png/'),
        ),
    ]
