# Generated by Django 5.0.6 on 2024-07-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_exp_alter_skill_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='desc1',
            new_name='desc_1',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='desc2',
            new_name='desc_2',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='desc3',
            new_name='desc_3',
        ),
    ]
